# Generated by Django 3.1 on 2022-01-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shipping_rules',
        ),
    ]
