# Generated by Django 3.1 on 2022-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20220116_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='handle_diameter',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
