# Generated by Django 3.1 on 2022-01-16 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_handle_diameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='handle_diameter',
            new_name='handle',
        ),
    ]
