# Generated by Django 3.1 on 2021-12-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211219_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='img/userprofile/default_profile.jpg', upload_to='userprofile'),
        ),
    ]
