# Generated by Django 3.1 on 2021-12-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211224_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', upload_to='userprofile'),
        ),
    ]
