# Generated by Django 3.1 on 2021-12-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211224_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='images/profile.jpg', upload_to='images'),
        ),
    ]
