# Generated by Django 3.1 on 2022-01-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='hero_title',
            field=models.CharField(max_length=200),
        ),
    ]
