# Generated by Django 3.1 on 2022-03-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimages',
            name='hero_position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
