# Generated by Django 3.1 on 2022-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20220106_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroimages',
            name='hero_title',
            field=models.TextField(max_length=200),
        ),
    ]
