# Generated by Django 3.1 on 2023-03-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_heroimages_hero_link_bgcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBannerFront',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField(blank=True, max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_files')),
                ('poster', models.ImageField(upload_to='images/posters/front')),
            ],
            options={
                'verbose_name': 'video_title',
            },
        ),
        migrations.CreateModel(
            name='VideoBannerInside',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.TextField(blank=True, max_length=200)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='post_files')),
                ('poster', models.ImageField(upload_to='images/posters/inside')),
            ],
            options={
                'verbose_name': 'video_title',
            },
        ),
    ]
