# Generated by Django 3.1 on 2023-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_videobannerfront_videobannerinside'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videobannerfront',
            options={'verbose_name': 'video_title_front', 'verbose_name_plural': 'video_title_front'},
        ),
        migrations.AlterModelOptions(
            name='videobannerinside',
            options={'verbose_name': 'video_title_inside', 'verbose_name_plural': 'video_title_inside'},
        ),
        migrations.AlterField(
            model_name='videobannerfront',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/front'),
        ),
        migrations.AlterField(
            model_name='videobannerfront',
            name='video_title',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videobannerinside',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/inside'),
        ),
        migrations.AlterField(
            model_name='videobannerinside',
            name='video_title',
            field=models.TextField(max_length=200),
        ),
    ]
