# Generated by Django 3.1 on 2023-03-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20230326_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobannerfront',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='videobannerinside',
            name='poster',
        ),
        migrations.AlterField(
            model_name='videobannerfront',
            name='video_file',
            field=models.FileField(blank=True, default='images/posters/inside', upload_to='videos/front'),
        ),
    ]
