# Generated by Django 3.1 on 2023-03-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20230329_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobannerfront',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/front'),
        ),
    ]
