# Generated by Django 3.1 on 2023-03-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20230329_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videobannerfront',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/front'),
        ),
        migrations.AlterField(
            model_name='videobannerinside',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/inside'),
        ),
    ]
