# Generated by Django 3.1 on 2021-12-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20211219_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Collect From Store', 'Collect From Store')], default='Shipping', max_length=30),
        ),
    ]
